import { ThemeType } from "./ThemeType";

export const darkColorSchema: ThemeType["colors"] = {
  background: "#121212",
  foreground: "#FFFFFF",
  surface: "#1E1E1E",
  primary: "#00675f",
  primaryMuted: "rgba(0, 170, 157, 0.16)",
  onPrimary: "#FFFFFF",
  onPrimaryMuted: "rgba(255, 255, 255, 0.18)",
  secondary: "#00aa9d",
  text: "#FFFFFF",
  mutedText: "#A6A6A6",
  border: "#ffffffde",
  shadow: "#000000",
  tabBarActiveTintColor: "#00aa9d",
  transparent: "transparent",
  returnBtnBackground: "#E4F3EA",
  activeIconColor: "#0C5347",
  unactiveIconColor: "#33473F",
  titleColor: "#FFFFFF",
  statusApprovedBackgroundColor: "#E4F3EA",
  statusExpiredColor: "#B54A40",
  statusExpiredBackgroundColor: "#F6E4E1",
  filterActiveBorderColor: '#1A8F6E',
};
